### ISSUE TITLE
Allow disabling the apt-get commands

### ISSUE THREAD

**Issue by mockjv** [crazy-max/ghaction-dump-context#13]
### Behaviour

Currently, the dump runs a `sudo apt-get` command if the runner is Linux, however, in a self-hosted environment the runner might not be running in such a state that the `sudo` command is allowed.

#### Steps to reproduce this issue

1. Deploy a self-hosted runner
2. Run the ghaction-dump-context action
3. Observe error about failure to execute sudo

#### Expected behaviour

> Possibly introduce an input or environment variable that could disable running the "Install deps" section.

#### Actual behaviour

```shell
Install deps
  /usr/bin/sudo apt-get update
  sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
Error: The process '/usr/bin/sudo' failed with exit code 1
```

### Configuration

* Repository URL (if public):  Not public
* Build URL (if public):  N/A

### Logs

[1_🚀 Setup (1).txt](https://github.com/crazy-max/ghaction-dump-context/files/11443781/1_.Setup.1.txt)

**Comment by crazy-max** [comment]
Good catch we could make this opt-in. Feel free to open a PR.

**Comment by schmidtw** [comment]
I needed something like this too, so I created #14 .  Instead of any additional inputs to control this, my changes check if the tools (`sudo`, `apt-get`, `cpuid`, etc) are available and gracefully skip the things that the environment doesn't allow for.
